import { Note, Review } from "./types";

export const INITIAL_NOTES: Note[] = [
  {
    id: "1",
    title: "Class 10 Higher Mathematics NCTB Exam Companion",
    titleBn: "১০ম শ্রেণীর উচ্চতর গণিত এনসিটিবি পরীক্ষার সহায়িকা",
    subject: "Mathematics",
    subjectBn: "গণিত",
    institution: "Notre Dame College, Dhaka",
    institutionBn: "নটর ডেম কলেজ, ঢাকা",
    course: "Higher Math (Chapter 8 & 11)",
    courseBn: "উচ্চতর গণিত (অধ্যায় ৮ এবং ১১)",
    price: 250.00,
    author: "Zakir Hossain Chowdhury",
    authorBn: "জাকির হোসেন চৌধুরী",
    rating: 4.8,
    ratingCount: 43,
    downloadCount: 198,
    pageCount: 32,
    fileType: "PDF",
    description: "Hand-compiled master notes covering Trigonometry and Coordinate Geometry for SSC candidates. Features clear proof derivations, board exam shortcuts, and step-by-step vector guides as taught in NDC.",
    descriptionBn: "এসএসসি পরীক্ষার্থীদের জন্য ত্রিকোণমিতি এবং স্থানাঙ্ক জ্যামিতির হাতে লেখা মাস্টার নোট। এতে এনডিসিতে শেখানো সহজ প্রমাণ, বোর্ড পরীক্ষার শর্টকাট কৌশল এবং ধাপে ধাপে ভেক্টর গাইড রয়েছে।",
    previewSnippet: [
      "## CHAPTER 8: TRIGONOMETRY FORMULAS & SHORTCUTS",
      "For concentric circular sectors, the relation s = rθ is critical. Note: θ must be evaluated in radians.",
      "",
      "### Common Trig Key Formulas & Relations:",
      "1. sin²θ + cos²θ = 1",
      "2. sec²θ - tan²θ = 1",
      "3. cosec²θ - cot²θ = 1",
      "",
      "### Coordinate Geometry Distance Formula: ",
      "Between points A(x₁, y₁) and B(x₂, y₂):",
      "d = √[(x₂ - x₁)² + (y₂ - y₁)²]",
      "",
      "### ND Collge Special Test Practice Question:",
      "Determine the area of a triangle with vertices P(2, -3), Q(6, 5) and R(-4, 2) using coordinate vectors."
    ],
    previewSnippetBn: [
      "## অধ্যায় ৮: ত্রিকোণমিতির সূত্রাবলি ও শর্টকাট",
      "কেন্দ্রীয় বৃত্তাকার চাপের জন্য সম্পর্ক s = rθ অত্যন্ত গুরুত্বপূর্ণ। মনে রাখবেন: θ অবশ্যই রেডিয়ানে থাকতে হবে।",
      "",
      "### সাধারণ ত্রিকোণমিতিক সূত্রসমূহ:",
      "১. sin²θ + cos²θ = ১",
      "২. sec²θ - tan²θ = ১",
      "৩. cosec²θ - cot²θ = ১",
      "",
      "### স্থানাঙ্ক জ্যামিতি দূরত্বের সূত্র:",
      "A(x₁, y₁) এবং B(x₂, y₂) বিন্দুর মধ্যবর্তী দূরত্ব:",
      "d = √[(x₂ - x₁)² + (y₂ - y₁)²]",
      "",
      "### নটর ডেম কলেজ বিশেষ পরীক্ষার প্রশ্ন:",
      "ডেক্স ভেক্টরের সাহায্য নিয়ে P(2, -3), Q(6, 5) এবং R(-4, 2) শীর্ষবিশিষ্ট ত্রিভুজের ক্ষেত্রফল নির্ণয় কর।"
    ],
    tags: ["Higher Math", "SSC", "Class 10", "NCTB", "Notre Dame"],
    uploadDate: "2026-05-12",
    sellerEmail: "zakir.ndc@example.com",
    thumbnailSeed: "math",
    featured: true,
    isOfficialTextbook: false,
    classLevel: "Class 10"
  },
  {
    id: "2",
    title: "Class 9 Physics: Force & Gravity Core Companion",
    titleBn: "৯ম শ্রেণীর পদার্থবিজ্ঞান: বল ও মহাকর্ষ মূল লেকচার শিট",
    subject: "Physics",
    subjectBn: "পদার্থবিজ্ঞান",
    institution: "Rajuk Uttara Model College, Dhaka",
    institutionBn: "রাজউক উত্তরা মডেল কলেজ, ঢাকা",
    course: "Physics Chapter 3 & 6",
    courseBn: "পদার্থবিজ্ঞান অধ্যায় ৩ এবং ৬",
    price: 180.00,
    author: "Fahmida Rahman",
    authorBn: "ফাহমিদা রহমান",
    rating: 4.9,
    ratingCount: 72,
    downloadCount: 245,
    pageCount: 20,
    fileType: "PDF",
    description: "Extremely clean class notes summarizing Newton's Laws of Motion, Momentum, Friction types, and Gravity formulas for NCTB Class 9 students. Includes full textbook math problem trace-outs.",
    descriptionBn: "এনসিটিবি ৯ম শ্রেণীর শিক্ষার্থীদের জন্য নিউটনের গতিসূত্র, ভরবেগ, ঘর্ষণের প্রকারভেদ এবং মহাকর্ষের সূত্রের অত্যন্ত পরিষ্কার ক্লাস নোট। এতে পাঠ্যবইয়ের অনুশীলনী অঙ্কের সম্পূর্ণ সমাধান রয়েছে।",
    previewSnippet: [
      "## LINEAR MOTION & FORCE - NEWTON'S SECOND LAW",
      "Rate of change of momentum is directly proportional to applied force, resulting in F = ma.",
      "",
      "### Essential Momentum Friction Formulas:",
      "1. Momentum (P) = mass (m) × velocity (v)",
      "2. Conservation of Momentum: m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂",
      "3. Friction Force (F_f) = μ × normal force (R)",
      "",
      "### Gravity & Accelation (g):",
      "g = GM / R² (Average value of g is 9.8 m/s² on Earth surface, zero at center).",
      "Weight (W) = mg"
    ],
    previewSnippetBn: [
      "## রৈখিক গতি ও বল - নিউটনের দ্বিতীয় সূত্র",
      "ভরবেগের পরিবর্তনের হার প্রযুক্ত বলের সমানুপাতিক, যার ফলস্বরূপ F = ma সূত্রটি পাওয়া যায়।",
      "",
      "### ভরবেগ ও ঘর্ষণের প্রয়োজনীয় সূত্রসমূহ:",
      "১. ভরবেগ (P) = ভর (m) × বেগ (v)",
      "২. ভরবেগের সংরক্ষণশীলতা নীতি: m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂",
      "৩. ঘর্ষণ বল (F_f) = μ × অভিলম্ব প্রতিক্রিয়া (R)",
      "",
      "### অভিকর্ষ ও ত্বরণ (g):",
      "g = GM / R² (পৃথিবীর পৃষ্ঠে g এর গড় মান ৯.৮ মি/সে², কেন্দ্রের দিকে গেলে ইহার মান শূন্য হয়)।",
      "ওজন (W) = mg"
    ],
    tags: ["Physics", "Force", "Gravity", "Class 9", "Rajuk"],
    uploadDate: "2026-04-28",
    sellerEmail: "fahmida.rumc@example.com",
    thumbnailSeed: "science",
    featured: true,
    isOfficialTextbook: false,
    classLevel: "Class 9"
  },
  {
    id: "3",
    title: "Class 10 Bangla Literary Analysis & Poetry Notes",
    titleBn: "১০ম শ্রেণীর বাংলা সাহিত্য বিশ্লেষণ ও কবিতা নোট",
    subject: "Bengali",
    subjectBn: "বাংলা",
    institution: "Viqarunnisa Noon School & College",
    institutionBn: "ভিকারুননিসা নূন স্কুল অ্যান্ড কলেজ",
    course: "Bangla Sahitya Konika",
    courseBn: "বাংলা সাহিত্য কণিকা",
    price: 150.00,
    author: "Shahnaz Parveen",
    authorBn: "শাহনাজ পারভীন",
    rating: 4.7,
    ratingCount: 31,
    downloadCount: 112,
    pageCount: 15,
    fileType: "PDF",
    description: "Ultimate summary notes on classic NCTB Bangla poems: 'Kopotakkho Nod', 'Kobor', and prose analyses including 'Shuva'. Created by VNSC senior Bengali department head designed for easy board score maximization.",
    descriptionBn: "ক্লাসিক এনসিটিবি বাংলা কবিতা: 'কপোতাক্ষ নদ', 'কবর' এবং 'শুভা'-সহ সকল মূল গদ্যের দারুণ বিশ্লেষণমূলক নোট। সহজে জিপিএ ৫ অর্জনের লক্ষ্য নিয়ে এটি ভিকারুননিসার সিনিয়র শিক্ষিকা দ্বারা রচিত।",
    previewSnippet: [
      "## POETRY SECTION: 'KOPOTAKKHO NOD' BY MICHAEL MADHUSUDAN DUTT",
      "This iconic sonnet celebrates the author's profound home-sickness and deep nostalgia for Jessore's river landscape while residing in France.",
      "",
      "### Key Theme Pillars:",
      "1. Patriotism (স্বদেশপ্রেম): Deep admiration for the homeland over alien lands.",
      "2. Rhyme Scheme (অমিল প্রবাহ): 8+6 structured sonnet flow (অষ্টক ও ষষ্টক)।",
      "",
      "### Core Board Analytical Question:",
      "Why does Madhusudan compare the water of Kopotakkho river to 'the milk stream of the mother's breast'?"
    ],
    previewSnippetBn: [
      "## কবিতা বিভাগ: মাইকেল মধুসূদন দত্ত রচিত 'কপোতাক্ষ নদ'",
      "এই অমর সনেটটিতে ফ্রান্সে অবস্থানকালে কবি যশোরের নদী ও পল্লী প্রকৃতির প্রতি তাঁর গভীর দেশপ্রেম ও শৈশবের নস্টালজিয়ার প্রকাশ ঘটিয়েছেন।",
      "",
      "### মূল ভাববস্তুর স্তম্ভসমূহ:",
      "১. স্বদেশপ্রেম: সুদূর পরবাসে থেকেও কবির মন জুড়ে ছিল কপোতাক্ষ নদের স্মৃতি।",
      "২. অমিত্রাক্ষর ছন্দ বিন্যাস: ক খ ক খ ক খ ক খ (অষ্টক) এবং গ ঘ গ ঘ গ ঘ (ষষ্টক)।",
      "",
      "### গুরুত্বপূর্ণ সৃজনশীল প্রশ্ন:",
      "কবি কেন কপোতাক্ষ নদের জলকে 'দুগ্ধ-স্রোতরূপী' মায়ের বুকের দুধের সাথে তুলনা করেছেন?"
    ],
    tags: ["Bangla", "Poetry", "SSC Note", "Class 10", "Viqarunnisa"],
    uploadDate: "2026-05-01",
    sellerEmail: "shahnaz.vnsc@example.com",
    thumbnailSeed: "nature",
    featured: true,
    isOfficialTextbook: false,
    classLevel: "Class 10"
  },
  {
    id: "4",
    title: "Official NCTB Class 8 Mathematics Govt Textbook",
    titleBn: "সরকারি এনসিটিবি ৮ম শ্রেণীর গণিত বোর্ড পাঠ্যবই",
    subject: "Mathematics",
    subjectBn: "গণিত",
    institution: "National Curriculum and Textbook Board",
    institutionBn: "জাতীয় শিক্ষাক্রম ও পাঠ্যপুস্তক বোর্ড",
    course: "Class 8 Math",
    courseBn: "৮ম শ্রেণী গণিত",
    price: 0.00,
    author: "National Curriculum Panel, Bangladesh",
    authorBn: "জাতীয় শিক্ষা বোর্ড প্যানেল, বাংলাদেশ",
    rating: 4.6,
    ratingCount: 120,
    downloadCount: 840,
    pageCount: 164,
    fileType: "PDF",
    description: "Official government textbook provided by National Curriculum and Textbook Board Bangladesh. Includes Pattern, Simple Profit, Set Theory, Rational Equations, and Geometry. Provided for free to ensure absolute equity.",
    descriptionBn: "জাতীয় শিক্ষাক্রম ও পাঠ্যপুস্তক বোর্ড বাংলাদেশ কর্তৃক প্রকাশিত সরকারি মূল পাঠ্যবই। এতে প্যাটার্ন, সরল মুনাফা, সেট তত্ত্ব, পরিমাপ এবং জ্যামিতির সকল অনুশীলনীর সমাধানযোগ্য ব্যাখ্যা রয়েছে। শিক্ষার্থীদের সুবিধার্থে বিনামূল্যে সংরক্ষিত।",
    previewSnippet: [
      "## CHAPTER 1: NUMBER PATTERNS & SEQUENCES",
      "A pattern is a regular, repeating arrangement of numbers or design structures.",
      "",
      "### Standard Pattern Relations:",
      "• Linear Pattern: nth term = a + (n - 1)d, where 'd' check difference.",
      "• Sum of first 'n' natural numbers = [n(n + 1)] / 2",
      "",
      "### Chapter 2: Profit Calculator Formula:",
      "• Simple Profit Formula: I = Prn",
      "• Compound Principal: C = P(1 + r)^n"
    ],
    previewSnippetBn: [
      "## অধ্যায় ১: সংখ্যার প্যাটার্ন ও অনুক্রম",
      "প্যাটার্ন হলো সংখ্যা বা নকশার একটি নির্দিষ্ট বিন্যাস যা নির্দিষ্ট নিয়ম মেনে চলতে থাকে।",
      "",
      "### সাধারণ প্যাটার্ন সূত্রাবলি:",
      "• রৈখিক প্যাটার্ন: কতম পদ = প্রথম পদ + (ক - ১) × সাধারণ পার্থক্য।",
      "• প্রথম 'ক' সংখ্যক জোড় সংখ্যার সমষ্টি = ক × (ক+১)",
      "",
      "### অধ্যায় ২: মুনাফার গাণিতিক হিসাব:",
      "• সরল মুনাফা সূত্র: I = Prn",
      "• চক্রবৃদ্ধি মূলধন: C = P(১ + r)^n"
    ],
    tags: ["Govt Book", "NCTB", "Math", "Class 8", "Bangladesh"],
    uploadDate: "2026-01-10",
    sellerEmail: "nctb.gov@example.com",
    thumbnailSeed: "books",
    featured: false,
    isOfficialTextbook: true,
    classLevel: "Class 8"
  },
  {
    id: "5",
    title: "Official NCTB Class 7 Science Experiential Book",
    titleBn: "সরকারি এনসিটিবি ৭ম শ্রেণীর বিজ্ঞান অনুসন্ধানী পাঠ বোর্ড বই",
    subject: "Science",
    subjectBn: "বিজ্ঞান",
    institution: "National Curriculum and Textbook Board",
    institutionBn: "জাতীয় শিক্ষাক্রম ও পাঠ্যপুস্তক বোর্ড",
    course: "Science (Inquiry)",
    courseBn: "বিজ্ঞান (অনুসন্ধানী পাঠ)",
    price: 0.00,
    author: "National Curriculum Panel, Bangladesh",
    authorBn: "জাতীয় শিক্ষা বোর্ড প্যানেল, বাংলাদেশ",
    rating: 4.5,
    ratingCount: 98,
    downloadCount: 712,
    pageCount: 142,
    fileType: "PDF",
    description: "Standard government digital textbooks for Class 7. Covers biodiversity, animal species, carbon dioxide pathways, force balance, earth structures, and physical states of matter. Offered free by NCTB.",
    descriptionBn: "৭ম শ্রেণীর নতুন শিক্ষা কারিকুলামের সরকারি অনুসন্ধানী বিজ্ঞানের বোর্ড বই। এতে জীববৈচিত্র্য, খাদ্যশৃঙ্খল, কার্বন চক্র, চাপ ও বলবিদ্যা এবং শক্তির উৎস সমূহের চমকপ্রদ ব্যাখ্যা রয়েছে। সম্পূর্ণ বিনামূল্যে ডাউনলোড করুন।",
    previewSnippet: [
      "## CHAPTER 2: CELL BIOLOGY AND STRUCTURES",
      "Understanding plant cells (containing cell walls and plastids) versus animal cells.",
      "",
      "### Cellular Comparison Check:",
      "1. Plant cell has a rigid cellulose cell wall; animal cell does not.",
      "2. Plastids (specifically Chloroplasts) enable plant photosynthesis; animal cells rely on eating existing organic sources."
    ],
    previewSnippetBn: [
      "## অধ্যায় ২: উদ্ভিদ ও প্রাণী কোষের গঠন",
      "উদ্ভিদ কোষ (যার কোষপ্রাচীর এবং প্লাস্টিড থাকে) এবং প্রাণী কোষের প্রধান গাঠনিক বৈচিত্র্যের তুলনা আলোচনা করা যাক।",
      "",
      "### কোষ গঠনগত তুলনামূলক বিশ্লেষণ:",
      "১. উদ্ভিদ কোষে শক্ত সেলুলোজ নির্মিত কোষপ্রাচীর থাকে; প্রাণী কোষে তা থাকে না।",
      "২. প্লাস্টিড (বিশেষ করে ক্লোরোপ্লাস্ট) উদ্ভিদের সালোকসংশ্লেষণে সাহায্য করে; প্রাণী খাদ্য তৈরি করতে পারে না।"
    ],
    tags: ["Govt Book", "NCTB", "Science", "Class 7", "Biodiversity"],
    uploadDate: "2026-01-15",
    sellerEmail: "nctb.gov@example.com",
    thumbnailSeed: "earth",
    featured: false,
    isOfficialTextbook: true,
    classLevel: "Class 7"
  },
  {
    id: "6",
    title: "Class 6 English 'Talk with People' Activity Notes",
    titleBn: "৬ষ্ঠ শ্রেণীর ইংরেজি 'টক উইথ পিপল' অ্যাক্টিভিটি নোট",
    subject: "English",
    subjectBn: "ইংরেজি",
    institution: "St. Joseph Higher Secondary School, Dhaka",
    institutionBn: "সেন্ট যোসেফ উচ্চ মাধ্যমিক বিদ্যালয়, ঢাকা",
    course: "English 1st Paper (New Curriculum)",
    courseBn: "ইংরেজি ১ম পত্র (নতুন কারিকুলাম)",
    price: 160.00,
    author: "Brother Donald Becker",
    authorBn: "ব্রাদার ডোনাল্ড বেকার",
    rating: 4.8,
    ratingCount: 19,
    downloadCount: 65,
    pageCount: 12,
    fileType: "PDF",
    description: "Conversational activity study notes mapped to the 2026 Class 6 curriculum. Features simplified pronoun worksheets, context dialogue builders, vocabulary synonyms, and polite expressions templates.",
    descriptionBn: "২০২৬ সালের নতুন কারিকুলাম অনুযায়ী প্রণীত ৬ষ্ঠ শ্রেণীর ইংরেজি কথোপকথন নোট। এতে প্রোনাউন ওয়ার্কশিট, দৈনন্দিন ডায়ালগ মেকার, শব্দার্থ ও মার্জিত শব্দ ব্যবহারের সহজ নিয়মের লিস্ট আছে। সেন্ট যোসেফের শিক্ষার্থীদের জন্য বিশেষভাবে প্রস্তুতকৃত।",
    previewSnippet: [
      "## UNIT 1: TALK WITH THE NEIGHBORS & PEOPLE",
      "Learning how to start a conversation in english with teachers, peers, and elderly relatives.",
      "",
      "### Direct Dialogue Matrix (Polite Expressions):",
      "• Instead of 'What do you want?' -> Use: 'How can I assist you today, sir?'",
      "• If excuse: 'I am so sorry to bother you, but could you repeat that please?'",
      "",
      "### Basic Grammar Checklist:",
      "- Nouns represent entities (e.g. Bangladesh, Book)."
    ],
    previewSnippetBn: [
      "## ইউনিট ১: মানুষের সাথে মার্জিত কথোপকথন",
      "ইংরেজি ভাষায় শিক্ষক, সহপাঠি ও বয়োজ্যেষ্ঠদের সাথে কথাবলার আদবকেতা নিয়ে প্রস্তুতকৃত লেকচার শিট।",
      "",
      "### সরাসরি কথোপকথন প্যাটার্ন (মার্জিত উত্তর):",
      "• 'আপনি কী চান?' এর পরিবর্তে বলুন -> 'আজ আপনাকে কীভাবে সাহায্য করতে পারি, স্যার?'",
      "• 'আমি দুঃখিত, দয়া করে কথাটি কি আরেকবার বলবেন?'",
      "",
      "### মৌলিক ব্যাকরণ তালিকা:",
      "- নাউন দ্বারা স্থান বা বস্তুকে বোঝায় (যেমন: বাংলাদেশ, বই)।"
    ],
    tags: ["English", "Grammar", "Class 6", "St Joseph", "Dialogue"],
    uploadDate: "2026-05-18",
    sellerEmail: "donald.stj@example.com",
    thumbnailSeed: "journal",
    featured: false,
    isOfficialTextbook: false,
    classLevel: "Class 6"
  },
  {
    id: "7",
    title: "Class 9 Chemistry: Periodic Table & Chemical Bonds Secrets",
    titleBn: "৯ম শ্রেণীর রসায়ন: পর্যায় সারণি ও রাসায়নিক বন্ধন নোট",
    subject: "Chemistry",
    subjectBn: "রসায়ন",
    institution: "Chittagong Collegiate School",
    institutionBn: "চট্টগ্রাম কলেজিয়েট স্কুল",
    course: "Chemistry Chapter 4 & 5",
    courseBn: "রসায়ন অধ্যায় ৪ এবং ৫",
    price: 220.00,
    author: "Pranab Kumar Das",
    authorBn: "প্রণব কুমার দাস",
    rating: 4.9,
    ratingCount: 54,
    downloadCount: 182,
    pageCount: 25,
    fileType: "PDF",
    description: "Highly rated chemistry notes parsing periodic criteria, atomic size trends, ionization potential patterns, and step by step ionic vs covalent compound bonding diagram guides.",
    descriptionBn: "পর্যায় সারণির সাধারণ ব্যতিক্রমসমূহ, পরমাণুর আকার হ্রাস-বৃদ্ধি, আয়নিকরণ শক্তির মান এবং আণবিক বন্ধন গঠনের অসাধারণ ডায়াগ্রাম শিট। ভালো রসায়ন নম্বর নিশ্চিত করার জন্য চট্টগ্রাম কলেজিয়েট স্কুলের প্রখ্যাত স্যার প্যানেল দ্বারা পরীক্ষিত।",
    previewSnippet: [
      "## CHAPTER 4: PERIODIC PROPERTIES MATRIX",
      "Within a period, as atomic number increases, atomic radius decreases because of nuclear charge pulls.",
      "",
      "### Core Ionic Bonding Diagram Example: NaCl",
      "• Sodium loses 1 valence electron: Na -> Na⁺ + e⁻",
      "• Chlorine gains 1 valence electron: Cl + e⁻ -> Cl⁻",
      "• Electrostatic attraction yields crystalline Lattice structure.",
      "",
      "### Periodic Trends Summary:",
      "- Ionization Energy increases left-to-right, decreases top-to-bottom."
    ],
    previewSnippetBn: [
      "## অধ্যায় ৪: পর্যায় সারণি ও আণবিক ধর্মাবলি",
      "একই পর্যায়ে যতই পারমাণবিক সংখ্যা বৃদ্ধি পায়, নিউক্লিয়াসের অধিক আকর্ষণের কারণে অবয়বের আকার হ্রাস পায়।",
      "",
      "### আয়নিক বন্ধনের ছবি ডায়াগ্রাম: NaCl",
      "• সোডিয়াম পরমাণু ১টি ইলেকট্রন বর্জন করে: Na -> Na⁺ + e⁻",
      "• ক্লোরিন পরমাণু ১টি ইলেকট্রন গ্রহণ করে: Cl + e⁻ -> Cl⁻",
      "• স্থির বৈদ্যুতিক আকর্ষণের ফলে শক্তিশালী আয়ন বন্ধন Lattice তৈরি করে।",
      "",
      "### পর্যায় সারণির পরিবর্তনের ছক:",
      "- তড়িৎ ঋণাত্মকতা বাম থেকে ডানে বৃদ্ধি পায়, উপর থেকে নিচে হ্রাস পায়।"
    ],
    tags: ["Chemistry", "Periodic Table", "Class 9", "SSC", "Chittagong"],
    uploadDate: "2026-05-19",
    sellerEmail: "pranab.ccs@example.com",
    thumbnailSeed: "science",
    featured: true,
    isOfficialTextbook: false,
    classLevel: "Class 9"
  },
  {
    id: "8",
    title: "Class 8 History & Social Science: Liberation War Chronology",
    titleBn: "৮ম শ্রেণীর ইতিহাস ও সামাজিক বিজ্ঞান: মহান মুক্তিযুদ্ধ ইতিহাসপঞ্জি",
    subject: "Social Science",
    subjectBn: "ইতিহাস ও সামাজিক বিজ্ঞান",
    institution: "Motijheel Government Boys High School",
    institutionBn: "মতিঝিল সরকারি বালক উচ্চ বিদ্যালয়",
    course: "History & Culture (Unit 4)",
    courseBn: "ইতিহাস ও সংস্কৃতি (ইউনিট ৪)",
    price: 190.00,
    author: "Anwarul Haque",
    authorBn: "আনোয়ারুল হক",
    rating: 4.7,
    ratingCount: 22,
    downloadCount: 99,
    pageCount: 14,
    fileType: "PDF",
    description: "Detailed, objective, highly informative chronological notes of Bangladesh's 1971 Liberation War. Focuses on the historic March 7 speech, the Mujibnagar Govt formation, and the ultimate victory roadmap.",
    descriptionBn: "১৯৭১ সালের মহান মুক্তিযুদ্ধের ইতিহাসপঞ্জির অত্যন্ত সুচারু ও নির্ভুল নোট। ৭ই মার্চের রূপরেখা, প্রবাসী মুজিবনগর সরকারের গঠন প্রক্রিয়া এবং ১৬ই ডিসেম্বর চূড়ান্ত বিজয়ের ঐতিহাসিক দিনসমূহ নিয়ে তৈরি। মতিঝিল সরকারি সরকারি উচ্চ বিদ্যালয়ের প্যানেল দ্বারা ট্রাস্টেড।",
    previewSnippet: [
      "## THE 1971 ROAD TO INDEPENDENCE - CHRONOLOGY",
      "Detailed review of major milestones and sacrifices that gave birth to Bangladesh.",
      "",
      "### Major Historic Events Timeline (1971):",
      "1. March 7: Bangabandhu delivering dynamic speech establishing freedom goals in Dhaka.",
      "2. March 25: Brutal Operation Searchlight initiated against sleeping civilians.",
      "3. April 17: Official oath of the provisional Mujibnagar Government in Meherpur.",
      "4. Dec 16: Complete victory and instrument of surrender signed at Dhaka.",
      "",
      "### Freedom Sectors Map Summary:",
      "Bangladesh was split into 11 geo-military tactical sectors under General M.A.G. Osmani."
    ],
    previewSnippetBn: [
      "## ১৯৭১ স্বাধীনতা অর্জনের মহাসড়ক - ইতিহাস ট্র্যাকার",
      "বাংলাদেশের গৌরবময় স্বাধীনতা যুদ্ধের সকল গুরুত্বপূর্ণ ঘটনার বিবরণ ও ইতিহাস শিট।",
      "",
      "### ১৯৭১ সালের চূড়ান্ত ঘটনাপ্রবাহের তালিকা:",
      "১. ৭ই মার্চ: রেসকোর্স ময়দানে বঙ্গবন্ধুর ঐতিহাসিক ভাষণের মাধ্যমে স্বাধীনতার ডাক।",
      "২. ২৫শে মার্চ: নিরস্ত্র ঘুমন্ত মুক্তিকামী বাঙালির উপর পাকিস্তানি হানাদার বাহিনীর নির্মম হত্যাযজ্ঞ (অপারেশন সার্চলাইট)।",
      "৩. ১৭ই এপ্রিল: মেহেরপুরের বৈদ্যনাথতলায় স্বাধীন বাংলাদেশের মুজিবনগর প্রবাসী সরকারের শপথ গ্রহণ।",
      "৪. ১৬ই ডিসেম্বর: হানাদার বাহিনীর চূড়ান্ত আত্মসমর্পণ ও স্বাধীন সার্বভৌম বাংলাদেশের অভ্যুদ্বয়।",
      "",
      "### সেক্টর বন্টনের তথ্য:",
      "মুক্তিযুদ্ধ পরিচালনার সুবিধার্থে সমগ্র দেশকে ১১টি রণকৌশলগত সামরিক সেক্টরে বিভক্ত করা হয়েছিল এবং প্রধান ছিলেন এম. এ. জি. ওসমানী।"
    ],
    tags: ["History", "Liberation War", "Class 8", "Motijheel Govt", "NCTB"],
    uploadDate: "2026-05-14",
    sellerEmail: "anwarul.mgb@example.com",
    thumbnailSeed: "law",
    featured: false,
    isOfficialTextbook: false,
    classLevel: "Class 8"
  }
];

export const MOCK_REVIEWS: Record<string, Review[]> = {
  "1": [
    { id: "r1", username: "SSC_Aspirant", rating: 5, comment: "This higher mathematics formula note saved me before my school pre-test. The Trigonometry details are fantastic!", date: "2026-05-20" },
    { id: "r2", username: "NotreDameFan", rating: 5, comment: "Excellent coordinate geometry tips. Typical NDC high quality.", date: "2026-05-28" }
  ],
  "2": [
    { id: "r3", username: "Fahim_Dhk", rating: 5, comment: "গতি ও বল অধ্যায়ের অঙ্কের জন্য এর থেকে ভালো গাইড পাইনি। খুবই চমৎকার!", date: "2026-05-15" }
  ],
  "3": [
    { id: "r4", username: "Tasnim_Vnsc", rating: 5, comment: "বাংলা সাহিত্যের কপোতাক্ষ নদের ছন্দের ব্যাখ্যাটি সবচেয়ে দারুণ লেগেছে। ধন্যবাদ আপা!", date: "2026-05-18" }
  ],
  "4": [
    { id: "r5", username: "TeacherBD", rating: 4, comment: "Official math textbooks, very clear scan. Great to have free math resources on Notecycle.", date: "2026-03-01" }
  ]
};

export const SUBJECT_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  "Mathematics": { bg: "bg-indigo-50 text-indigo-700 border-indigo-200", text: "text-indigo-700", border: "border-indigo-200" },
  "Science": { bg: "bg-emerald-50 text-emerald-700 border-emerald-200", text: "text-emerald-700", border: "border-emerald-200" },
  "Physics": { bg: "bg-blue-50 text-blue-700 border-blue-200", text: "text-blue-700", border: "border-blue-200" },
  "Chemistry": { bg: "bg-teal-50 text-teal-700 border-teal-200", text: "text-teal-700", border: "border-teal-200" },
  "Bengali": { bg: "bg-rose-50 text-rose-700 border-rose-200", text: "text-rose-700", border: "border-rose-200" },
  "English": { bg: "bg-amber-50 text-amber-700 border-amber-200", text: "text-amber-700", border: "border-amber-200" },
  "Social Science": { bg: "bg-violet-50 text-violet-700 border-violet-200", text: "text-violet-700", border: "border-violet-200" },
  "Other": { bg: "bg-slate-50 text-slate-700 border-slate-200", text: "text-slate-700", border: "border-slate-200" }
};
